import './compatibility.js';
import './editor-engine.js';

import '../app/app.js';
import '../app/app.routes.js';
import '../app/app.controller.js';
import '../app/directives/dragnode.directive.js';
import '../app/directives/dropnode.directive.js';
import '../app/directives/keytable.directive.js';
import '../app/directives/tab.directive.js';
import '../app/directives/tabset.directive.js';
import '../app/models/project.model.js';
import '../app/models/settings.model.js';
import '../app/pages/dash/dash.controller.js';
import '../app/pages/editor/components/menubar.controller.js';
import '../app/pages/editor/components/nodespanel.controller.js';
import '../app/pages/editor/components/propertiespanel.controller.js';
import '../app/pages/editor/components/treespanel.controller.js';
import '../app/pages/editor/editor.controller.js';
import '../app/pages/editor/modals/editnode.controller.js';
import '../app/pages/editor/modals/export.controller.js';
import '../app/pages/editor/modals/import.controller.js';
import '../app/pages/home/home.controller.js';
import '../app/pages/projects/projects.controller.js';
import '../app/pages/settings/settings.controller.js';
import '../app/services/dialog.service.js';
import '../app/services/editor.service.js';
import '../app/services/nodejs.service.js';
import '../app/services/notification.service.js';
import '../app/services/storage/filestorage.service.js';
import '../app/services/storage/localstorage.service.js';
import '../app/services/storage/storage.service.js';
import '../app/services/system.service.js';
import '../app/validators/blacklist.directive.js';

export var appModule = window.angular.module('app');
